### ISSUE TITLE
Examples doesn't work with Python 3.4

### ISSUE THREAD

**Issue by hnykda** [hovel/pybbm#181]
Hello,

I wanted to try this package and it's examples, but none of it worked for me. Mainly because of Python 2 x Python 3 incompabilities, like printing without parenthesis and so on. I used 2to3, but then I ended up with 

```
~ python manage.py runserver
  File "/home/dan/prac/.virtualenvs/bbforum/lib/python3.4/site-packages/common/fields.py", line 6, in <module>
    from django.utils import simplejson
ImportError: cannot import name 'simplejson
```
and I gave up. Python 3.4.

So I tried with Python 2. Now I'm getting this error:

```
~ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
```

**Comment by lampslave** [comment]
`django.utils.simplejson` was replaced by `json`. Carry on please :)

**Comment by skolsuper** [comment]
The package is also tested with python3.4 for django>=1.5 and passes: https://travis-ci.org/hovel/pybbm

You python 2 failure looks like a problem with your virtualenv.

**Comment by lampslave** [comment]
Please update packages and check the settings.
